# Generated by Django 4.2.28 on 2026-02-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=2048)),
                ('lob_owner', models.CharField(max_length=32, verbose_name='LOB Owner')),
                ('it_owner', models.CharField(max_length=32, verbose_name='IT Owner')),
                ('department', models.CharField(choices=[('Insurance', 'Insurance'), ('Claims', 'Claims'), ('Membership', 'Membership'), ('Travel', 'Travel'), ('ERS', 'ERS'), ('D&R', 'D&R'), ('IT', 'IT'), ('HR', 'HR'), ('Others', 'Others')], max_length=32)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Pilot', 'Pilot'), ('In-progress', 'In-progress'), ('Planning', 'Planning')], max_length=32)),
                ('technology', models.CharField(max_length=32)),
                ('value', models.TextField(max_length=1024)),
                ('benefit_name', models.CharField(max_length=64)),
                ('benefit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealizedBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('benefit_type', models.CharField(choices=[('Dollars saved', 'Dollars saved'), ('Hours saved', 'Hours saved'), ('Revenue increased', 'Revenue increased'), ('Member Acquired', 'Member Acquired')], max_length=64)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realized_benefits', to='initiatives.initiative')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('initiative', 'month', 'benefit_type')},
            },
        ),
    ]
