# Generated by Django 4.2.28 on 2026-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='it_owner_email',
            field=models.EmailField(default='it@example.com', max_length=128, verbose_name='IT Owner Email'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name',
            field=models.CharField(default='Untitled Initiative', max_length=32),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='benefit_name',
            field=models.CharField(choices=[('Productivity Gain', 'Productivity Gain'), ('New Business', 'New Business')], max_length=32),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='department',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Claims', 'Claims'), ('Membership', 'Membership'), ('Travel', 'Travel'), ('Automotive Services', 'Automotive Services'), ('D&R', 'D&R'), ('IT', 'IT'), ('Human Resources', 'Human Resources'), ('Experience Organization', 'Experience Organization'), ('Data/Insight', 'Data/Insight'), ('Finance & Procurement', 'Finance & Procurement'), ('Field Operations', 'Field Operations')], max_length=32),
        ),
    ]
