# Generated by Django 4.2.28 on 2026-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_initiative_it_owner_email_initiative_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realizedbenefit',
            unique_together={('initiative', 'month')},
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='benefit',
        ),
        migrations.AddField(
            model_name='initiative',
            name='kpi_name',
            field=models.CharField(blank=True, help_text='Name of the KPI to be tracked', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='multiplier_dollars',
            field=models.FloatField(default=0, help_text='KPI x this = dollars saved'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='multiplier_minutes',
            field=models.FloatField(default=0, help_text='KPI x this = minutes saved'),
        ),
        migrations.AddField(
            model_name='realizedbenefit',
            name='calculated_dollars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realizedbenefit',
            name='calculated_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realizedbenefit',
            name='kpi_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realizedbenefit',
            name='revenue_impact',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='realizedbenefit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='realizedbenefit',
            name='benefit_type',
        ),
    ]
