# Generated by Django 4.2.28 on 2026-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_alter_realizedbenefit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='kpi_name',
            field=models.CharField(blank=True, help_text='Name of the KPI to be tracked', max_length=32, null=True),
        ),
    ]
