# Generated by Django 4.2.28 on 2026-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_alter_initiative_kpi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='kpi_name',
            field=models.CharField(blank=True, help_text='Name of the KPI to be tracked', max_length=64, null=True, verbose_name='KPI Name'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='multiplier_dollars',
            field=models.FloatField(default=0, help_text='Minutes saved x this = dollars saved'),
        ),
    ]
