# Generated by Django 4.2.28 on 2026-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_alter_initiative_kpi_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='value',
            field=models.TextField(max_length=1024, verbose_name='Business Value'),
        ),
    ]
