# Generated by Django 4.2.28 on 2026-02-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_alter_initiative_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizedbenefit',
            name='calculated_dollars',
        ),
        migrations.RemoveField(
            model_name='realizedbenefit',
            name='calculated_minutes',
        ),
    ]
