# Generated by Django 4.2.28 on 2026-02-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_remove_realizedbenefit_calculated_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='webhook_key',
            field=models.CharField(blank=True, help_text='Secret key for external reporting via webhook', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WebhookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('payload', models.JSONField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiatives.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
