# Generated by Django 4.2.28 on 2026-02-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_initiative_webhook_key_webhookauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View')], max_length=16)),
                ('object_type', models.CharField(max_length=32)),
                ('object_name', models.CharField(max_length=256)),
                ('user', models.CharField(default='AnonymousUser', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Portal', 'Portal'), ('API', 'API')], default='Portal', max_length=16)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
