# Generated by Django 4.2.28 on 2026-02-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View'), ('Export', 'Export'), ('Import', 'Import')], max_length=16),
        ),
    ]
