# Generated by Django 4.2.28 on 2026-02-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0010_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('icon', models.CharField(help_text="Path or class for the icon (e.g., 'fas fa-server' or '/static/img/icon.png')", max_length=255)),
                ('max_consumption', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='initiative',
            name='benefit_name',
            field=models.CharField(choices=[('Productivity Gain', 'Efficiency Gain'), ('New Business', 'New Business')], max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='department',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Claims', 'Claims'), ('Membership', 'Membership'), ('Travel', 'Travel'), ('Automotive Services', 'Automotive Services'), ('D&R', 'D&R'), ('IT', 'IT'), ('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Data/Insight', 'Data/Insight'), ('Finance & Procurement', 'Finance & Procurement'), ('Field Operations', 'Field Operations'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='it_owner',
            field=models.CharField(max_length=100, verbose_name='IT Owner'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='lob_owner',
            field=models.CharField(max_length=100, verbose_name='LOB Owner'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(default='Untitled Initiative', max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='requester_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Pilot', 'Pilot'), ('In-progress', 'In-progress'), ('Planning', 'Planning')], max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='technology',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TechnologyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Format: YYYY-MM-01')),
                ('consumption', models.FloatField(default=0.0)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='initiatives.technology')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('technology', 'month')},
            },
        ),
    ]
